/*
 * Info.java
 *
 * Created on 10 de Abril de 2005, 14:56
 */

package com.erkobridee.calculadora.lexica.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 * GUI de informação da calculadora léxica
 *
 * @author <a href="mailto:erko.bridee@gmail.com">Erko Bridee de Almeida Cabrera</a>
 */
public class InfoPrograma  extends javax.swing.JFrame {
    
    /**
     * <code>actionHandle</code> -
     * tratador de eventos de botões da classe 
     */
    private ActionHandle actionHandle = new ActionHandle();
    
    /** Creates new form Info */
    public InfoPrograma() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        infoTabs = new javax.swing.JTabbedPane();
        calculosAba = new javax.swing.JPanel();
        scrollCalculosPane = new javax.swing.JScrollPane();
        calculosAreaText = new javax.swing.JTextArea();
        infoAba = new javax.swing.JPanel();
        programaImageLabel = new javax.swing.JLabel();
        programaName = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        titleDescricaoLabel = new javax.swing.JLabel();
        descricaoArea = new javax.swing.JTextArea();
        autorAba = new javax.swing.JPanel();
        autorLabel = new javax.swing.JLabel();
        autorImageLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        autorMailLabel = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        descricaoArea1 = new javax.swing.JTextArea();
        sairButton = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setTitle("Info");
        setIconImage( Img.getImage("info.png") );
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm();
            }
        });

        infoTabs.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        calculosAba.setLayout(new javax.swing.BoxLayout(calculosAba, javax.swing.BoxLayout.X_AXIS));

        calculosAreaText.setEditable(false);
        calculosAreaText.setText("\tCalculos Process\u00e1veis:\n\n\t<express\u00e3o> =\n Fatorial:\t\t<termo> !\n Potencia\u00e7\u00e3o:\t\t<termo> ^ <termo>\n\n Multiplica\u00e7\u00e3o:\t\t<termo> * <termo>\n Divis\u00e3o:\t\t<termo> / <termo>\n Resto Divis\u00e3o:\t\t<termo> % <termo>\n\n Soma:\t\t<termo> + <termo>\n Subtra\u00e7\u00e3o:\t\t<termo> - <termo>");
        scrollCalculosPane.setViewportView(calculosAreaText);

        calculosAba.add(scrollCalculosPane);

        infoTabs.addTab("Calculos", Img.getIcon("funct.png"), calculosAba);

        infoAba.setLayout(null);

        programaImageLabel.setIcon( Img.getIcon("calculos.gif") );
        infoAba.add(programaImageLabel);
        programaImageLabel.setBounds(10, 10, 80, 80);

        programaName.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        programaName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programaName.setText("Calculos - Calculadora L\u00e9xica");
        infoAba.add(programaName);
        programaName.setBounds(60, 20, 270, 15);

        versionLabel.setText("vers\u00e3o: 1.0,    Abril de 2005");
        infoAba.add(versionLabel);
        versionLabel.setBounds(120, 40, 240, 15);

        titleDescricaoLabel.setText("Descri\u00e7\u00e3o:");
        infoAba.add(titleDescricaoLabel);
        titleDescricaoLabel.setBounds(120, 80, 240, 15);

        descricaoArea.setEditable(false);
        descricaoArea.setFont(new java.awt.Font("Arial", 0, 10));
        descricaoArea.setTabSize(4);
        descricaoArea.setText("        Trabalho da disciplina de Compiladores, ano 2005\n \n\tCalculadora l\u00e9xica que analisa uma express\u00e3o \n   matem\u00e1tica repassada em modo texto e calcula \n   o seu resultado. \n\n\tVer aba calculos para saber quais opera\u00e7\u00f5es \n   s\u00e3o processadas por esta calculadora.");
        descricaoArea.setOpaque(false);
        infoAba.add(descricaoArea);
        descricaoArea.setBounds(50, 100, 280, 110);

        infoTabs.addTab("Programa", Img.getIcon("programa.gif"), infoAba);

        autorAba.setLayout(null);

        autorLabel.setText("Erko Bridee de Almeida Cabrera");
        autorAba.add(autorLabel);
        autorLabel.setBounds(170, 20, 200, 15);

        autorImageLabel.setIcon( Img.getIcon("autor.jpg") );
        autorAba.add(autorImageLabel);
        autorImageLabel.setBounds(10, 10, 90, 70);

        nomeLabel.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        nomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeLabel.setText("Nome : ");
        autorAba.add(nomeLabel);
        nomeLabel.setBounds(100, 20, 60, 15);

        emailLabel.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("E-mail : ");
        autorAba.add(emailLabel);
        emailLabel.setBounds(100, 40, 60, 15);

        autorMailLabel.setText("erko.bridee@gmail.com");
        autorAba.add(autorMailLabel);
        autorMailLabel.setBounds(170, 40, 170, 15);

        emailLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        emailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel1.setText("Sobre : ");
        autorAba.add(emailLabel1);
        emailLabel1.setBounds(100, 80, 60, 15);

        descricaoArea1.setEditable(false);
        descricaoArea1.setFont(new java.awt.Font("Arial", 0, 10));
        descricaoArea1.setTabSize(4);
        descricaoArea1.setText("Cursando 4\u00ba ano, curso de Ci\u00eancia da Computa\u00e7\u00e3o\nCesufoz, Foz do Igua\u00e7u - Paran\u00e1");
        descricaoArea1.setOpaque(false);
        autorAba.add(descricaoArea1);
        descricaoArea1.setBounds(50, 100, 280, 110);

        infoTabs.addTab("Autor", Img.getIcon("web.png"), autorAba);

        getContentPane().add(infoTabs);
        infoTabs.setBounds(15, 10, 380, 240);

        sairButton.setText("Sair");
        sairButton.setIcon( Img.getIcon("close.png") );
        sairButton.setToolTipText("Fechar janela");
        sairButton.setBorder(null);
        sairButton.addActionListener( actionHandle );
        getContentPane().add(sairButton);
        sairButton.setBounds(150, 260, 100, 25);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-415)/2, (screenSize.height-330)/2, 415, 330);
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm() {
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new InfoPrograma().show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autorAba;
    private javax.swing.JLabel autorImageLabel;
    private javax.swing.JLabel autorLabel;
    private javax.swing.JLabel autorMailLabel;
    private javax.swing.JPanel calculosAba;
    private javax.swing.JTextArea calculosAreaText;
    private javax.swing.JTextArea descricaoArea;
    private javax.swing.JTextArea descricaoArea1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JPanel infoAba;
    private javax.swing.JTabbedPane infoTabs;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel programaImageLabel;
    private javax.swing.JLabel programaName;
    private javax.swing.JButton sairButton;
    private javax.swing.JScrollPane scrollCalculosPane;
    private javax.swing.JLabel titleDescricaoLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
    
    /*------------------------------------------------------------------------*
     *  Tratadores de eventos
     *------------------------------------------------------------------------*/
    private class ActionHandle implements ActionListener {
        public void actionPerformed(ActionEvent event) {
            if( event.getSource() == sairButton ) {
                exitForm();
            }
        }        
    }
    /*------------------------------------------------------------------------*
     *  Fim Tratadores de eventos
     *------------------------------------------------------------------------*/
}
