/*
 * DefineMascara.java
 *
 * Created on 29 de Setembro de 2005, 16:49
 */

package com.erkobridee.PID.GUI;

/**
 *
 * @author <a href="mailto:erko.bridee@gmail.com">Erko Bridee de Almeida Cabrera</a>
 */
public class DefineMascara extends  javax.swing.JDialog {
    
    private boolean aplica;
    
    private double[][] mascara;
        
    public DefineMascara( java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelMain = new javax.swing.JPanel();
        buttonAplica = new javax.swing.JButton();
        buttonCancela = new javax.swing.JButton();
        jPanelMatriz = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();

        setTitle("Mascara");
        /*
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });*/

        int W = 220;
        int H = 170;
        
        jPanelMain.setLayout(null);
        jPanelMain.setPreferredSize(new java.awt.Dimension(W, H));
        
        buttonAplica.setText("Aplica");
        buttonAplica.setMnemonic('A');
        buttonAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAplicaActionPerformed(evt);
            }
        });

        jPanelMain.add(buttonAplica);
        buttonAplica.setBounds(20, 140, 90, 23);

        buttonCancela.setText("Cancela");
        buttonCancela.setMnemonic('C');
        buttonCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelaActionPerformed(evt);
            }
        });

        jPanelMain.add(buttonCancela);
        buttonCancela.setBounds(110, 140, 90, 23);

        jPanelMatriz.setLayout(null);

        jPanelMatriz.setBorder(new javax.swing.border.TitledBorder("Valores"));
        jTextField1.setColumns(3);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("-1");
        jTextField1.setDragEnabled(true);
        jPanelMatriz.add(jTextField1);
        jTextField1.setBounds(20, 20, 40, 20);

        jTextField2.setColumns(3);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("-1");
        jPanelMatriz.add(jTextField2);
        jTextField2.setBounds(80, 20, 40, 20);

        jTextField3.setColumns(3);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("-1");
        jPanelMatriz.add(jTextField3);
        jTextField3.setBounds(140, 20, 40, 20);

        jTextField4.setColumns(3);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("-1");
        jPanelMatriz.add(jTextField4);
        jTextField4.setBounds(20, 50, 40, 20);

        jTextField5.setColumns(3);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("9");
        jPanelMatriz.add(jTextField5);
        jTextField5.setBounds(80, 50, 40, 20);

        jTextField6.setColumns(3);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("-1");
        jPanelMatriz.add(jTextField6);
        jTextField6.setBounds(140, 50, 40, 20);

        jTextField7.setColumns(3);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("-1");
        jPanelMatriz.add(jTextField7);
        jTextField7.setBounds(20, 80, 40, 20);

        jTextField8.setColumns(3);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("-1");
        jPanelMatriz.add(jTextField8);
        jTextField8.setBounds(80, 80, 40, 20);

        jTextField9.setColumns(3);
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("-1");
        jPanelMatriz.add(jTextField9);
        jTextField9.setBounds(140, 80, 40, 20);

        jPanelMain.add(jPanelMatriz);
        jPanelMatriz.setBounds(10, 10, 200, 120);

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-W)/2, (screenSize.height-H)/2, W, H);
        pack();
    }//GEN-END:initComponents

    
    /*
     * TODO: FUTURAMENTE TRATAR DE ERROS OU COISAS QUE NÃO DEVEM SER FEITAS
     */
    
    private void recuperaMascara() {
        this.setMascara( new double[3][3] );
                
        this.getMascara()[0][0] = Double.parseDouble( jTextField1.getText() );
        this.getMascara()[0][1] = Double.parseDouble( jTextField2.getText() );
        this.getMascara()[0][2] = Double.parseDouble( jTextField3.getText() );
        this.getMascara()[1][0] = Double.parseDouble( jTextField4.getText() );
        this.getMascara()[1][1] = Double.parseDouble( jTextField5.getText() );
        this.getMascara()[1][2] = Double.parseDouble( jTextField6.getText() );
        this.getMascara()[2][0] = Double.parseDouble( jTextField7.getText() );
        this.getMascara()[2][1] = Double.parseDouble( jTextField8.getText() );
        this.getMascara()[2][2] = Double.parseDouble( jTextField9.getText() );
        
    }
    
    private void buttonAplicaActionPerformed(java.awt.event.ActionEvent evt) {        
        this.recuperaMascara();        
        this.setAplica( true );
        this.dispose();
    }

    private void buttonCancelaActionPerformed(java.awt.event.ActionEvent evt) {
        this.setAplica( false );
        this.dispose();
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DefineMascara(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAplica;
    private javax.swing.JButton buttonCancela;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMatriz;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    
    /**
     * @return boolean aplica.
     */
    public boolean isAplica() {
        return aplica;
    }
    /**
     * @param boolean aplica
     */
    public void setAplica(boolean aplica) {
        this.aplica = aplica;
    }
    /**
     * @return double[][] mascara.
     */
    public double[][] getMascara() {
        return mascara;
    }
    /**
     * @param double[][] mascara
     */
    public void setMascara(double[][] mascara) {
        this.mascara = mascara;
    }
}
